### ISSUE TITLE
Add ORCID links to all authors

### ISSUE THREAD

**Issue by AntonPetrov** [Rfam/rfam-website#18]
Each author name should appear on a separate line in DESC files followed by ORCID id:

```
AU Author AB 0000-0000-0000-0000
```

- [x] add ORCID to curation tools
- [x] display on the website

[Mapping spreadsheet](https://docs.google.com/spreadsheets/d/19MUvX3QpsMbTLkmCLBXkvQfayqwS_lJyO8FXKvPkZd0/edit?usp=sharing)

**Comment by kalvari** [comment]
The format of the AU line can be one of the following
AU Author AB; 0000-0000-0000-0000
AU Author AB

The author lines should match the regular expression:
/^((\S+\s{1}\S{1,3})((\;\s{1})|$)(((\d{4}-){3})\d{3}(\d{1}|X))?){1}$/

It allows up to 3 initials for the author followed by '; ' and orcid if available
The regex also takes into account the case of orcids with the check digit being an X
