### ISSUE TITLE
Indexing new data for release 13.0

### ISSUE THREAD

**Issue by AntonPetrov** [Rfam/rfam-website#19]
We need to add **Genome** as a fourth entity type in Rfam search in addition to Family, Clan, and Motif.

The Genome object should contain the following fields:

- [ ] `uniprot_reference_proteome_id` - empty if UPID not available
- [ ] `rfam_genome_id` - empty if UPID is available
- [x] `gca_accession` - empty if GCA not available
- [x] `description`
- [x] `length` - in nucleotides
- [x] `taxonomy_lineage` - string like `Bacteria; Firmicutes; etc`
- [x] `ncbi_taxonomy_id ` cross reference - see comment below
- [x] `num_rfam_hits` - number of significant Rfam family hits
- [x] `num_rfam_families` - number of distinct Rfam families with significant hits

**Comment by kalvari** [comment]
We need to rename gca_accesison to something else as we also have GCF accessions for a small  number of  genomes I downloaded from ncbi

**Comment by AntonPetrov** [comment]
Correction: `ncbi_taxid` should be a cross-reference like `<ref dbkey="9606" dbname="ncbi_taxonomy_id"/>`

**Comment by AntonPetrov** [comment]
New field request: let's add a **faceted** popular species field, same as in Family xml object:
- [ ] `<field name="popular_species">9606</field>`

**Comment by AntonPetrov** [comment]
Update: `num_rfam_families` should be `num_families`because this field is already used in clans objects

**Comment by AntonPetrov** [comment]
We also need to add **Match** as a fifth entry type:

- [ ] `entry_type` = `Match`
- [ ] `rfamseq_acc`
- [ ] `seq_start`
- [ ] `seq_end`
- [ ] `cm_start`
- [ ] `cm_end`
- [ ] `evalue_score`
- [ ] `bit_score`
- [ ] `alignment_type` - either `full` or `seed`. Should be a faceted field.
- [ ] `truncated` - one of 0, 5, 3, 53
- [ ] `common_name`
- [ ] `scientific_name`
- [ ] `<ref>` to Rfam family
- [ ] `<ref>` to `ncbi_taxonomy_id`
- [ ] `<ref>` to ENA accession
- [ ] `<ref>` to UPID

Only _significant_ hits should be indexed.
