### ISSUE TITLE
Broken links for accession numbers

### ISSUE THREAD

**Issue by JoannaArgasinska** [Rfam/rfam-website#3]
On the browse Rfam families website the links for the accession numbers are broken. 
http://rfam.xfam.org/families/with_structure#0%20-%209

**Comment by AntonPetrov** [comment]
The actual links are clearly broken:
http://rfam.xfam.org/family/RfamWeb::Model::RfamDB::Family=HASH(0x7fcdd9049e10)

**Comment by AntonPetrov** [comment]
Should be fixed on the test site now. Thanks for reporting this!
