### ISSUE TITLE
Incomplete Rfam.tar.gz mapping for Rfam>=14.0

### ISSUE THREAD

**Issue by filipsPL** [Rfam/rfam-website#34]
It seems that the file containing mapping of rfam families to pdb codes is incomplete in rfam 14.0 and 14.1.

In 14.0 (ftp://ftp.ebi.ac.uk/pub/databases/Rfam/14.0/Rfam.tar.gz) pdb code is missing:

```
pdb_id	chain	pdb_start	pdb_end	bit_score	evalue_score	cm_start	cm_end	hex_colour
RF00001	C	3	118	77.20	1.6e-20	1	119	0064f4
RF00001	9	1	121	77.40	1.4e-20	1	119	ebeb30
RF00001	9	1	121	77.40	1.4e-20	1	119	93c090
RF00001	B	1	121	77.40	1.4e-20	1	119	c008ae
RF00001	B	1	121	77.40	1.4e-20	1	119	8484c0
```

In 14.1 (ftp://ftp.ebi.ac.uk/pub/databases/Rfam/14.1/Rfam.pdb.gz) the header is missing and there is no rfam ids:

```
3hjw	D	1	57	48.50	1.3e-11	1	70	1fc01f
3lwo	D	1	57	48.50	1.3e-11	1	70	ff87a4
3lwp	D	1	57	48.50	1.3e-11	1	70	ebeb30
3lwq	D	1	57	48.50	1.3e-11	1	70	f29242
3lwr	D	1	57	48.50	1.3e-11	1	70	8585e6
```

**Comment by kalvari** [comment]
@filipsPL thank you for reporting this. You must have meant the `Rfam.pdb.gz` files, which I updated both and are now available on the `ftp`. 

[Rfam PDB 14.0](ftp://ftp.ebi.ac.uk/pub/databases/Rfam/14.0/Rfam.pdb.gz)
[Rfam PDB 14.1](ftp://ftp.ebi.ac.uk/pub/databases/Rfam/14.1/Rfam.pdb.gz)

**Comment by filipsPL** [comment]
Thank you, now it works perfectly! :+1:
