### ISSUE TITLE
 Sequence download extracts the wrong sequences

### ISSUE THREAD

**Issue by kalvari** [Rfam/rfam-website#37]
Sequence download is not working correctly. The sequence extracted isn't the correct one. For example there is an inconsistency between the `SEED` sequence of family `RF00005` 

AM286415.1/4382210-4382145
GAAGGCACGACAUUGCUCACAUUGCUUCCAGUGUUUACUU-AGCCAGC---CGGG-UGCUGGCUUUUUUUU 

and the sequence downloaded directly from the website: 

AM286415.1/4382210-4382145
CTTCCGTGCTGTAACGAGTGTAACGAAGGTCACAAATGAATCGGTCGGCCCACGACCGAAAAAAAA

**Comment by AntonPetrov** [comment]
Fixed with bf1eb687
