### ISSUE TITLE
Duplicate PDBe IDs

### ISSUE THREAD

**Issue by JoannaArgasinska** [Rfam/rfam-website#5]
Some PDB IDs are duplicated in the structure section.  For example, RF00037 has 3snp listed twice.

**Comment by AntonPetrov** [comment]
It's okay to have a family map to several chains in the same PDB file, as is the case for 3snp in [RF00037]
(http://rfam.xfam.org/family/RF00037#tabview=tab6):
![screen shot 2016-04-21 at 14 33 31](https://cloud.githubusercontent.com/assets/432675/14710627/0f934c26-07ce-11e6-996f-9a6297eca7e9.png)
Feel free to reopen the issue if you find another example of duplicate PDB ids.
