### ISSUE TITLE
rchie view to be updated

### ISSUE THREAD

**Issue by JoannaArgasinska** [Rfam/rfam-website#6]
rchie view wasn't updated

**Comment by AntonPetrov** [comment]
Will be fixed in the new release when it comes out. For more details see: https://gist.github.com/AntonPetrov/c35b79f9bc14bb9d98bcf1fa9c93e0f8

**Comment by AntonPetrov** [comment]
Before vs after comparison of Rchie diagrams for the tRNA family:
http://codepen.io/antonpetrov/pen/GZQPEy

**Comment by AntonPetrov** [comment]
Fixed in release 12.1
